UN-OCHA/docstore-site

README.md, html/modules/custom/docstore/src/Controller/VocabularyController.php, html/modules/custom/docstore/src/MetadataTrait.php, html/modules/custom/docstore/syncs/create_disasters.php
The changes to MetadataTrait.php need checking - the rest should be straight-forward.
=> [DOC-24] small issues noticed in passing

git-hooks/pre-commit, git-hooks/scripts/pre-commit/lint-common, git-hooks/scripts/pre-commit/lint-php, git-hooks/scripts/pre-commit/lint-phpcs, git-hooks/scripts/pre-commit/lint-sass, phpcs.xml
Ticket: DOC-40
This simply adds the pre-commit git hooks to validate the code before committing like done on other websites (SLT, GHO etc.).
Normally it's compatible with Docksal.
=> [DOC-40] Add pre-commit hooks

html/modules/custom/docstore/src/Controller/VocabularyController.php, html/modules/custom/docstore/src/ManageFields.php
This picks up another 'undefined variable' error and avoids an error in creating vocabulary fields if the field already exists.
=> Doc 24 small fixes

.github/workflows/docker-build-image.yml, docker/Dockerfile
FYI, it *should* also be possible to bump the docstore to the PHP 7.4 images.
=> [OPS-7307] Docstore feature build

html/modules/custom/docstore/src/Controller/DocumentTypeController.php, html/modules/custom/docstore/src/ManageFields.php, html/modules/custom/docstore/src/SearchableResourceTrait.php
=> DOC-53: Index per node type

html/modules/custom/docstore/src/Controller/DocumentController.php
Ticket: AR-217
This PR adds support for list of files in the form
```json
[{
"uuid": "media-uuid-1"
},{
"uuid": "media-uuid-2"
}]
```
which is what is sent by the assessment registry site for `assessment document` entities.
=> [AR-217] Allow arrays of files with the 'uuid' property

html/modules/custom/docstore/syncs/docstore_local_coordination_groups.php
No rush on this, but it should be included eventually.
=> [AR-224] add translation for Colombia

composer.json, composer.lock
https://humanitarian.atlassian.net/browse/DOC-63
Security update to facets module
=> [DS-63] update facets to 1.8.0

composer.json, composer.lock, html/modules/custom/docstore/syncs/docstore_local_coordination_groups.php
https://humanitarian.atlassian.net/browse/DS-63
=> [DS-63] facets security update

html/modules/custom/docstore/syncs/docstore_locations_display_name.php
https://humanitarian.atlassian.net/browse/AR-240
Script to add display name (including all parents) to locations.
=> [AR-240] add display name for locations

html/modules/custom/docstore/src/Commands/DocstoreCommands.php
Updates the command to handle admin_levels. Assuming (for the display_name) that children are likely to be created after the parents, as the HRinfo api is sorted by id.
=> [AR-240] update locations command to handle admin_levels as they are

composer.lock, html/modules/custom/docstore/src/Commands/DocstoreCommands.php
https://humanitarian.atlassian.net/browse/OPS-7724
(and an unrelated clarification for a drush command).
=> [OPS-7724] update admin_toolbar

composer.lock
https://humanitarian.atlassian.net/browse/OPS-7780
=> [OPS-7634] update core to 9.2.6

html/modules/custom/docstore/docstore.module, html/modules/custom/docstore/docstore.routing.yml, html/modules/custom/docstore/src/Controller/DocumentTypeController.php, html/modules/custom/docstore/src/ManageFields.php
Example output
```json
{
"total": 8623,
"remaining": 8623,
"indexed": 0,
"missing_fields": [
"local_groups"
],
"document_fields": [
"nid",
"uuid",
"vid",
....
],
"indexed_fields": [
"_stored_entity_fields",
"ar_date",
"ar_status",
"ar_status_label_",
....
]
}
```
=> Ar 240 status endpoint

.travis.yml, composer.json, composer.lock, config/core.extension.yml
https://humanitarian.atlassian.net/browse/OPS-8028
https://humanitarian.atlassian.net/browse/OPS-8029
=> [OPS-8028] update core to 9.3.3

composer.json, composer.lock, html/modules/custom/docstore/src/Controller/FileController.php, html/modules/custom/docstore/src/Plugin/Field/FieldWidget/SelectedFileVersionWidget.php, html/modules/custom/docstore/src/ProviderTrait.php, html/modules/custom/docstore/src/SearchableResourceTrait.php
https://humanitarian.atlassian.net/browse/OPS-7997
Update dev modules
=> [OPS-7997] update dev modules

html/modules/custom/docstore/src/Commands/DocstoreCommands.php
- updateClusters
- updateOperations
- updateOrganizations
Refs: #AR-279
=> feat: Sync from HRInfo

composer.lock
[OPS-8203]
update search_api module to 1.23.0
[OPS-8203]: https://humanitarian.atlassian.net/browse/OPS-8203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OPS-8203] update search_api module to 1.23.0

Makefile, tests/docker-compose.yml
Companion commit to https://github.com/UN-OCHA/docstore-stack/pull/49
=> chore: update local image name

composer.lock
=> chore: update composer.lock

composer.lock
=> Deploy 27-07-2022

composer.lock
Refs: [OPS-8550](https://humanitarian.atlassian.net/browse/OPS-8550)
Core and module updates
=> Deployment 17-08-2022

composer.lock
=> [OPS-8560] monthly module updates

.github/workflows/composer-update.yml, composer.lock
=> [OPS-8623] core security update 

.dockerignore, docker/Dockerfile
=> chore: update dockerfile and dockerignore

docker/Dockerfile
=> Core security update

composer.json, composer.lock
=> chore: remove preserve-paths package

.github/workflows/run-tests.yml, composer.json, composer.lock
[OPS-9560](https://humanitarian.atlassian.net/browse/OPS-9560): module updates
[OPS-9560]: https://humanitarian.atlassian.net/browse/OPS-9560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Deploy 20-09-2023

composer.lock
=> chore:  SA-CORE-2023-006
