- html/modules/custom/docstore/docstore.routing.yml
- html/modules/custom/docstore/src/Controller/DocumentController.php
- html/modules/custom/docstore/src/Controller/DocumentReadController.php
- html/modules/custom/docstore/src/Controller/DocumentTypeController.php
- html/modules/custom/docstore/src/Controller/DownloadController.php
- html/modules/custom/docstore/src/Controller/ProviderController.php
- html/modules/custom/docstore/src/Controller/VocabularyController.php
- html/modules/custom/docstore/src/Controller/WebhookController.php
- html/modules/custom/docstore/src/DocumentTypeTrait.php
- html/modules/custom/docstore/src/MetadataTrait.php
- html/modules/custom/docstore/src/ProviderTrait.php
- html/modules/custom/docstore/src/ResourceTrait.php
- tests/run.sh
- tests/silk_document_crud.md
- tests/silk_files.md
- tests/silk_private.md
- tests/silk_webhooks.md
Ticket: DOC-41
This moves common code to parse request's content, check provider rights (can create/update/delete, can read, is owner etc.) and handle response (json response, cacheable json response etc.) to traits to consolidate the API's behavior and to help if we want to add some logging for example.
There is a new `ResourceTrait` for the request parsing and response handling. 
Provider checks were moved to the `ProviderTrait` though there is still the `providerCanUseField()` on the MetadataTrait as it's relevant there as well and the `providerCanUseVocabulary()` is also still in the `VocubularyController`. @attiks What do you think?
I also changed the `types` route to use the `{type}` parameter instead of `{node_type}` because it was confusing to have `$node_type` mean either the …
> [DOC-41] Consolidate responses

- html/modules/custom/docstore/syncs/create_disasters.php
- html/modules/custom/docstore/syncs/create_hrinfo_documents.php
- html/modules/custom/docstore/syncs/docstore_local_coordination_groups.php
Replacing https://github.com/UN-OCHA/hrinfo-site/pull/971, this is based on the similar scripts for AR and KM.
There are some extra debugging messages, and there's a limit on the quantity of files, so as not to overload the staging site, but it adds a load of hrinfo documents and should be able to handle the rest.
It should maybe use a couple more vocabularies in common with AR, and there's some discussion to be had about which should be shared with other sites.
Some of the naming of fields in HRinfo is confusing, this sticks close to the names in the API, but the naming should probably be improved now to make it more clear in the future.
> Sync HRInfo docs

- html/modules/custom/docstore/docstore.routing.yml
- html/modules/custom/docstore/src/Controller/DocumentController.php
- html/modules/custom/docstore/src/Controller/VocabularyController.php
- tests/silk_document_bulk_cud.md
- tests/silk_vocabulary_bulk_cud.md
Ticket: DOC-22
Follow-up of https://github.com/UN-OCHA/docstore-site/pull/80 allowing POST, PUT, PATCH and DELETE methods on the BULK endpoints rather than using an `_action` property on the elements.
@attiks, please merge this PR to update #80 (it's against `feature/doc-22-bulk`) if you think that approach is better than the `_action` version.
> [DOC-22] Use http methods rather than _action property for bulk endpoints

- html/modules/custom/docstore/docstore.module
- html/modules/custom/docstore/docstore.routing.yml
- html/modules/custom/docstore/src/Controller/DocumentController.php
- html/modules/custom/docstore/src/Controller/DocumentReadController.php
- html/modules/custom/docstore/src/Controller/DocumentTypeController.php
- html/modules/custom/docstore/src/Controller/VocabularyController.php
- html/modules/custom/docstore/src/Controller/WebhookController.php
- html/modules/custom/docstore/src/DocumentTypeTrait.php
- html/modules/custom/docstore/src/ManageFields.php
- html/modules/custom/docstore/src/MetadataTrait.php
- html/modules/custom/docstore/src/ProviderTrait.php
- tests/run.sh
- tests/silk_document_bulk.md
- tests/silk_document_bulk_cud.md
- tests/silk_document_crud.md
- tests/silk_document_revisions.md
- tests/silk_vocabulary_bulk.md
- tests/silk_vocabulary_bulk_cud.md
- tests/silk_vocabulary_crud.md
Ticket: DOC-22
The primary goal of this PR is to allow create, update and delete operations when querying the documents or terms bulk endpoints by specifying for each items in the list the type of action via a `_action` property.
When the `_action` is not provided, it's considered a `create` operation for compatibility with the existing behavior of the `bulk` endpoints. Maybe we can remove this and always require the `_action` to be defined.
Currently the 3 actions are:
- `create`
- `update` (full update equivalent to a PUT)
- `delete`
Maybe we could allow partial updates via a `partial_update` action. That would be easy to add code-wise. Thoughts?
The returned data is a list of json objects with the `entity uuid` and `message` (ex: Term created) when the operation for the corresponding …
> [DOC-22] Allow create, update and delete operations with bulk endpoints

- .travis.yml
- tests/docker-compose.yml
- tests/settings/services.yml
- tests/settings/settings.test.php
This PR changes the travis config to build an image with the latest code and run the tests inside a container using that image.
This is notably to be able to tests changes made to nginx to handle access to files which the tests rely on.
This also has the advantage of being closer to what is on production.
> Change travis to build docker image and run tests from it

- html/modules/custom/docstore/src/Controller/FileController.php
Ticket: AR-217
This moves the media entity creation after the file entity has been saved when creating a file resource so that the file entity has an id.
This doesn't really do much aside of ensuring the first revision has the proper message: "File created" instead of "File updated" (see `FileTrait::saveMedia()`).
> [AR-217] Create media after file entity has been saved so it has an id

- html/modules/custom/docstore/docstore.module
- html/modules/custom/docstore/src/Controller/DocumentController.php
- html/modules/custom/docstore/src/Controller/DocumentTypeController.php
- html/modules/custom/docstore/src/Controller/FileController.php
- html/modules/custom/docstore/src/Controller/TermController.php
- html/modules/custom/docstore/src/Controller/VocabularyController.php
- html/modules/custom/docstore/src/ManageFields.php
- tests/run.sh
- tests/silk_webhooks.md
- tests/webhooks/index.php
Ticket: DOC-59
This consolidates the webhook events and allow to subscribe to notifications for CUD operations on all document types/vocabularies or specific ones. It also adds notifications for files.
The notifications only contain the resource id/uuid and eventually resource type depending on the event and it's the responsibility of the subscriber to retrieve the full data afterwards.
This is to avoid issues with private content. For example if provider A listens to events on the doc type `truc` and provider B creates a private `truc` document then, the provider A shouldn't not receive data that it would not have access to normally which could happen if we were to pass the entire resource data to the webhooks.
An alternative but more expensive option, could be to load all the registered …
> [DOC-59] Update webhooks

- html/modules/custom/docstore/syncs/docstore_local_coordination_groups.php
This is primarily for the Local coordination groups field on https://assessments.hpc.tools/assessment/add - I looked at altering just the options, but as this field is useless without the context of its operation, I think it's worth having in the title in the docstore.
Not sure whether it should be `<local group> - <operation>` or `<local group> [<operation>]`, but I think either is okay.
> Add operation to local group title

- html/modules/custom/docstore/syncs/docstore_local_coordination_groups.php
Added a last minute 'tidy' that interrupts the script: https://jenkins.aws.ahconu.org/view/Docstore/job/docstore-dev-drush/87/console Reverting.
> revert tiny cleanup that stops script running

- html/modules/custom/docstore/syncs/docstore_local_coordination_groups.php
Got an error on jenkins run that I can't reproduce locally. This tiny change might let me understand it better.
(The suggestion on https://jenkins.aws.ahconu.org/view/Docstore/job/docstore-dev-drush/88/console to use --no-halt-on-error wasn't useful: https://jenkins.aws.ahconu.org/view/Docstore/job/docstore-dev-drush/89/console)
> adjust print statement to understand error on jenkins only

- docker/etc/nginx/custom/01_docstore_files.conf
- html/modules/custom/docstore/docstore.routing.yml
- html/modules/custom/docstore/src/Controller/DownloadController.php
- html/modules/custom/docstore/src/Controller/FileController.php
- html/modules/custom/docstore/src/FileTrait.php
- tests/run.sh
- tests/silk_files_direct.md
Ticket: OPS-7373
*Note: this is not necessary for the Assessment Registry launch and only changes internally the way access to the private files is handled.*
Follow-up of https://github.com/UN-OCHA/docstore-site/pull/96 that changes the handling of private files.
This removes the symlinks with tokens for private files. Instead the docstore nginx calls an api endpoint to check if the provider has access to the file and if that's the case serves the file. 
That means that to access a private file, a client needs to add the `API-KEY` header to the request to the `/files` endpoint.
Symlinks are only used to connect a `media` to a `file`, with the possibility to point at a different version for a given provider.
> [OPS-7373] Add endpoint to check for private file access

- README.md
- html/modules/custom/docstore/src/Commands/DocstoreCommands.php
- html/modules/custom/docstore/src/ResourceTrait.php
- html/modules/custom/docstore/syncs/docstore_local_coordination_groups.php
- tests/run.sh
- tests/silk_create.md
- tests/silk_document_bulk_cud.md
- tests/silk_document_crud.md
- tests/silk_exceptions.md
Noting that there might be some changes with fixing the 'taxonomy' typo - at the moment it's using 'name' for taxonomy terms, which is wished for in the 'todo'.
Also, not sure if this is the right place to index the display name, or if we want to use 'display_name' as a standard and index those if they exist for other referenced entities.
> [AR-224] index display name

- html/modules/custom/docstore/docstore.routing.yml
- html/modules/custom/docstore/src/Controller/TermController.php
- html/modules/custom/docstore/src/SearchableResourceTrait.php
For AR I need a quick way to get all terms from a vocabulary, doing a loadMultiple on external entities is way to slow (8-10 seconds), so the idea was to add a new endpoint to the docstore so I can fetch all terms (uuid, label and display_name) at once. With an empty cache it takes around 2-3 seconds, all next calls are "instant"
PS: Code is a bit messy
Code from AR can be found at https://github.com/UN-OCHA/assessmentregistry8-site/pull/244/commits/f9fb8e074ee4638c323fbeadb5f90b2d10001a02
> Add endpoint to get all terms at once

- html/modules/custom/docstore/docstore.install
Adds display name to locations, and to the search index.
(Still requires re-running sync script and the script to populate the display names).
> [AR-240] add display_name for locations

- html/modules/custom/docstore/src/Controller/DocumentController.php
Ticket: AR-249
Doing a SolR request just to get one document is overkill and may cause issues when the request is performed before SolR has finished indexing the content. So just get the data from the DB.
Note: we should do the same for the `DocumentController::getDocumentRevisions` and `DocumentController::getDocumentFiles` and `TermController::getTerm`.
> [AR-249] Do not use Solr to get a single document

- html/modules/custom/docstore/src/Commands/DocstoreCommands.php
Vocabulary load syntax was wrong, but didn't get discovered until scripts needed to create a new term.
This simplifies it.
> [AR-240] remove redundant vocabulary load - which did not work

- html/modules/custom/docstore/src/Commands/DocstoreCommands.php
Testing on dev produced errors when trying to load non-existing tids.
e.g. https://jenkins.aws.ahconu.org/view/Docstore/job/docstore-dev-drush/125/console
This is some if statements to avoid that.
> [AR-240] guard against loading empty tids

- html/modules/custom/docstore/src/Commands/DocstoreCommands.php
Locations were getting imported multiple times as the id field wasn't getting populated. This fixes that.
> [AR-240] populate both id fields

- composer.json
- composer.lock
- html/modules/custom/docstore/src/Controller/DocumentController.php
- html/modules/custom/docstore/src/Controller/FileController.php
- html/modules/custom/docstore/src/Controller/TermController.php
- html/modules/custom/docstore/src/FileTrait.php
- html/modules/custom/docstore/src/MetadataTrait.php
- html/modules/custom/docstore/src/UtilityTrait.php
- tests/run.sh
- tests/silk_uuids.md
Ticket: RW-45
This PR enables passing a UUID when creating a document, term or file. A check is performed to ensure the UUID is valid and not in use.
When creating a new file resource and passing a UUID, it used for the media entity. The associated file entity's uuid is derived from it.
This change allows an easy mapping between for RW nodes and files, for example, as using UUIDs v3 and the node/file URLs we have constant UUIDs. This would help a lot migrating the content to the docstore in a predictable and reproducible manner.
> [RW-45] Allow passing UUID

- html/modules/custom/docstore/src/Commands/DocstoreCommands.php
As per the comment in https://github.com/UN-OCHA/docstore-site/pull/168, changing the 'author' for disasters from 'RW' to 'Shared'.
> [AR-240] adjust author name

- html/modules/custom/docstore/src/Controller/DocumentController.php
- html/modules/custom/docstore/src/Controller/FileController.php
- tests/silk_uuids.md
Payload is the following, but code tries to recreate the file, but this is already created using the file endpoint.
```php
Array
(
[title] => sdfsdf
[author] => BihGBBZgN4a5gj96
[files] => Array
(
[0] => Array
(
[uuid] => 68b76739-7ae6-4f42-b9ce-1c359b0a1059
[filename] => 2.pdf
[uri] => http://docstore.local.docksal/files/68b76739-7ae6-4f42-b9ce-1c359b0a1059/2.pdf
)
)
)
```
> Problem adding existing file

- composer.patches.json
This addresses the failure in https://jenkins.aws.ahconu.org/job/docstore-dev-deploy/209/console - not sure how we (or anyone else) didn't hit it before.
> [DOC-65] add patch for entity_reference_uuid module

- composer.lock
Ticket: DOC-70
This bumps the version of user_bundle 1.1.0 so it's compatible with the current Drupal core version. That notably fixes an issue preventing the creation of a user via the UI.
1. Checkout `develop` and to create a user via the UI (/admin/people  -> "add user"), you should get a PHP error
2. Checkout this branch (DOC-70), run composer install and check that it's now possible to create a user via the UI
> [DOC-70] Bump user_bundle module version

- html/modules/custom/docstore/src/Controller/FileController.php
- html/modules/custom/docstore/src/FileTrait.php
- tests/run.sh
- tests/silk_file_revisions.md
Ticket: DOC-71
This fixes the deletion of a file revision (i.e. now only the revision is deleted instead of the entire file resource) as well as a few issues with the file usage endpoint.
A new series of tests in `tests/silf_file_revisions.md` have been added to cover that part.
> [DOC-71] Fix file revision deletion and file usage

- composer.json
- docker/Dockerfile
Refs: DOC-75
Details on the ticket - but Docstore doesn't have a custom theme so shouldn't miss these commands, even if it doesn't solve the main issue.
> fix: remove gulp commands

- composer.json
- composer.lock
Refs: OPS-9403
Not sure why these modules were pinned - if there's a reason to leave them as they were, would be good to add it to the README file.
> chore: unpin modules from dev versions
